### ISSUE TITLE
The --reuse_zarr flag and memory use

### ISSUE THREAD

**Issue by erikenbody** [ksamuk/pixy#10]
Hi there,

Thanks for making this nice software, it is both convenient and accurate!

I have a large WGS dataset for which I am calculating diversity stats within and among many populations. E.g., I have 10 populations and I will run all pairwise combinations (1Gbp genome, 20x coverage per sample). 

What I did was run a first pass calculation for a single population pair, which generated the zarr directories for the full dataset. The diversity statistics were accurate based on my own calculations. I subsequently ran other contrasts with the --reuse-zarr flag. I was surprised to find that for a single chromosome the run took nearly 8 hours and exceeded 120Gb memory. 

This may just be a consequence of my dataset, but I wondered if this is the expected behavior? My limited experience with zarr databases is that they should be fairly efficient to open and run calculations. I was wondering if e.g. the VCF validation step (line 2 below) is part of the memory consumption? 

Or otherwise, if you have any other recommendations for a workflow here, I would appreciate it! It would be useful to know if this is expected (I can add more memory)  or if I am missing a key element here. 

```
[pixy] pixy version 0.95.0
[pixy] Validating VCF and input parameters (this may take some time)...
[pixy] WARNING: --bypass_filtration is set to 'yes', genotype filtration will be not be performed.
[pixy] EXTREME WARNING: --bypass_invariant_check is set to 'yes', which assumes that your VCF contains invariant sites. Lack of invariant sites will result in incorrect estimates.
[pixy] Preparing for calculation of summary statistics: pi,fst,dxy
[pixy] Data set contains 2 population(s), 1 chromosome(s), and 64 sample(s)
[pixy] Started calculations at 00:36:04
[pixy] If a zarr array exists, it will be reused for chromosome chr1...
[pixy] Calculating statistics for chromosome chr1...
[pixy] Pi calculations for chromosome chr1 complete and written to /crex/proj/snic2020-2-19/private/wagtail/users/erikenbody/07_pixy/species/west_flava_citrine/pixy_west_flava_citrine_1_pi.txt
[pixy] Dxy calculations chromosome chr1 complete and written to /crex/proj/snic2020-2-19/private/wagtail/users/erikenbody/07_pixy/species/west_flava_citrine/pixy_west_flava_citrine_1_dxy.txt
[pixy] Fst calculations chromosome chr1 complete and written to /crex/proj/snic2020-2-19/private/wagtail/users/erikenbody/07_pixy/species/west_flava_citrine/pixy_west_flava_citrine_1_fst.txt

[pixy] All calculations complete at 00:36:04
[pixy] Time elapsed: 07:48:10
```

My commands with some bash variables included
```
  pixy --stats pi fst dxy \
  --vcf $VCF \
  --zarr_path $WORK_D/zarr_east_west_flava_pixy.txt_${SLURM_ARRAY_TASK_ID} \
  --reuse_zarr	yes \
  --window_size 5000 \
  --populations $POPS_FILE \
  --bypass_filtration yes \
  --bypass_invariant_check yes \
  --fst_maf_filter 0.05 \
  --outfile_prefix $WORK_D/${OUTNAME}/pixy_${OUTNAME}_${SLURM_ARRAY_TASK_ID}
```

**Comment by ksamuk** [comment]
Hi there! Thanks for making us aware of this. We are going to greatly improving memory usage (and removing the Zarr format entirely for various reasons) in the next version of pixy. Stay tuned! In the mean time, the best way to deal with this would be partition your VCF into smaller chunks before running pixy.

**Comment by erikenbody** [comment]
Thanks! Good to know. I'll close this and look forward to the future improvements
