### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by willright28** [ksamuk/pixy#11]
Hi，
I managed to install pixy in Linux as your instruction, it seemed work:`# All requested packages already installed.`, but when I input `pixy --help`, it said `bash: pixy: command not found...`.
Any suggestions? 
Thanks in advaced!

**Comment by ksamuk** [comment]
Hi there! That's an odd problem, I assume you created an environment, activated it, and then installed pixy, and you are still in the activate environment? What does 'which pixy' return?

**Comment by willright28** [comment]
> Hi there! That's an odd problem, I assume you created an environment, activated it, and then installed pixy, and you are still in the activate environment? What does 'which pixy' return?

Hi!
It's my BIG mistake not install pixy in an environment.
Thanks for reply!

**Comment by ksamuk** [comment]
No problem, hope pixy works for your analysis!
