### ISSUE TITLE
max () arg is an empty sequence

### ISSUE THREAD

**Issue by nitinra** [ksamuk/pixy#13]
Hello, 

I am running pixy with the following commad:
`pixy --stats pi fst dxy --vcf allsamples_ldpruned.vcf --zarr_path ./zarr --window_size 10000 --populations allpop.list --bypass_filtration yes --bypass_invariant_check yes  --outfile_prefix results/`

This is the error I am running into after the pipeline as run midway:

> Traceback (most recent call last):
  File "/home/nitinr/.conda/envs/pixy/bin/pixy", line 11, in <module>
    sys.exit(main())
  File "/home/nitinr/.conda/envs/pixy/lib/python3.8/site-packages/pixy/__main__.py", line 482, in main
    interval_end = max(pos_array)
ValueError: max() arg is an empty sequence

**Comment by ksamuk** [comment]
Just checking in here, looks like you got things running based on your other issue. I'll close this for now but let me know if the issue persists.
