### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by mlaylwar** [ksamuk/pixy#15]
Hi,

I'm trying to run pixy for the first time but am encountering the following error message:

 File "/home/anaconda3/bin/pixy", line 11, in <module>
    sys.exit(main())
  File "/home/anaconda3/lib/python3.8/site-packages/pixy/__main__.py", line 220, in main
    os.mkdir(re.sub(r"[^\/]+$", "", args.outfile_prefix))
FileNotFoundError: [Errno 2] No such file or directory: ''

Any idea what could be causing this issue? 

The command that I have used is as follows
pixy --stats pi --vcf haploid_3_filtered_depth2.recode.vcf --populations popFile --zarr_path zarr --bypass_filtration yes --outfile_prefix 3xDP2

Many thanks!

**Comment by ksamuk** [comment]
Hi there! Due to a quirk that will be changed in the next version, outfile_prefix needs an output folder AND a prefix, so something like:
  `--outfile_prefix output/3xDP2` should fix it!

**Comment by mlaylwar** [comment]
Ok, great, thanks! That has sorted it.
