### ISSUE TITLE
Issue in D xy calculation

### ISSUE THREAD

**Issue by Doniol-Valcroze** [ksamuk/pixy#23]
Using pixy on Linux.
When trying **pixy --stats dxy --vcf filtered.sans.outgroup.nomissing.recode.vcf.gz --populations pixy_Med_E_NS.txt --window_size 100000 --n_cores 80 --bypass_invariant_check yes --output_prefix Med_E_Atl**

The command only calculate de Dxy on 5 chromosomes (+ half oh the 6th) out of the 10 chromosomes of my VCF and displays :

**The above exception was the direct cause of the following exception:
UnboundLocalError: local variable 'pixy_output' referenced before assignment**

Tried with and without the --output_prefix command without succes.

Any solution known for this kind of problem?

**Comment by ksamuk** [comment]
Hi There! Some things we can do to try to track this down:

1. Can you try rerunning the command with the '--debug' flag and pasting the resulting python traceback here?
2. Can you try to see what exactly is different about the region of the genome on the 6th chromosome where pixy fails? Are there long runs of missing data or the like?
3. Alternatively, can you provide a link to a subset of your data, ideally the region of the VCF where pixy fails? You can have a look at the temp file pixy created to see the last window that was successfully calculated. You can subset your VCF with tabix like: 

```
tabix your.vcf.gz chr6:600000:70000

**Comment by ksamuk** [comment]
Hi there, I believe this issue is now fixed in version 1.0.3.beta1, which is now on conda. Can you try updating pixy ('conda update pixy' in your pixy environment), and seeing if you still get the error?

**Comment by ksamuk** [comment]
Hi @Doniol-Valcroze, I'm going to close this issue for now. Please let me know if it reoccurs when using the new version.

**Comment by ksamuk** [comment]
Hi @Doniol-Valcroze, I'm going to close this issue for now. Please let me know if it reoccurs when using the new version.
