### ISSUE TITLE
Missing comma in requirements for setup.py

### ISSUE THREAD

**Issue by mishaploid** [ksamuk/pixy#24]
Hi Kieran, thanks so much for developing this really great and user friendly tool! Sharing a very minor "bug" that there is a comma missing in the requirements section of `setup.py` between 'scikit-allel' and 'pandas', so this throws an error of `Missing dependencies for scikit-allelpandas` if you try to install from source. 

For a little more background in case it's helpful for someone else, I was attempting to use pixy with a conda environment that has snakemake installed, but was running into issues with environment inconsistency (even in a fresh virtual environment). So I ended up installing from github with pip (via the virtual environment).

**Comment by ksamuk** [comment]
Hi Sarah, thanks very much for catching this! Its fixed now and will be updated on the conda version soon.
