### ISSUE TITLE
vcf file indexing error

### ISSUE THREAD

**Issue by sandipmkale** [ksamuk/pixy#27]
Hello,

I have indexed the vcf file with 
$tabix -Cp vcf filename command.
But I am getting "Exception: [pixy] ERROR: The vcf is not indexed with tabix." error.

Can you please help.

With best regards

Sandip

**Comment by ksamuk** [comment]
Hi Sandip,

Did that command produce a .tbi file? I'm not sure if the CSI format (-C flag) is supported by scikit-allel, can you try:

`$ tabix your.vcf.gz` 

Kieran

**Comment by sandipmkale** [comment]
No. as I mentioned, the chromosome is very big and .tbi can't be generated. I use flag -C to generate .csi. I think, I have to split the chromosome.

Thanks alot.

**Comment by ksamuk** [comment]
Hi Sandip,

The .csi format isn't supported unfortunately, so you will indeed have to split your chromosome. If scitkit-allel adds support for .csi indexes, we'll be able to supports these in the future. Cheers,

Kieran
