### ISSUE TITLE
KeyError: nan

### ISSUE THREAD

**Issue by djeffares** [ksamuk/pixy#31]
Dear Kieran Samuk

Thanks for making pixy, it is a very valuable tool.

I am having an error with running pixy that I can't diagnose. I would very much appreciate some guidance. At the moment pixy starts to calculate stats, then fails with: KeyError: nan.  The only outputs file (pixy_tmpfile_8ba3a11fae0041409dabd3d62ea4f743.tmp) is blank. All the details are below.

best wishes,
Daniel Jeffares

I am using an all sites bgzipped, tabix-indexed vcf created with freebayes:
freebayes -f hg38_pvivP01.fa bams/*bam \
--min-mapping-quality 30 \
--min-coverage 10 \
--strict-vcf \
--gvcf \
--report-monomorphic \
--vcf PvP01_01_v1.vcf &

I am running pixy on a mac. My command is:
pixy --stats pi fst dxy \
--vcf PvP01_01_v1.vcf.gz \
--populations popfile2.txt \
--window_size 10000 \
--output_prefix pixytest

The error code I get is:
[pixy] pixy 1.0.4.beta1
[pixy] See documentation at https://pixy.readthedocs.io/en/latest/

[pixy] Validating VCF and input parameters...
[pixy] Checking write access...OK
[pixy] Checking CPU configuration...OK
[pixy] Checking for invariant sites...OK
[pixy] Checking chromosome data...OK
[pixy] Checking intervals/sites...OK
[pixy] Checking sample data...OK
[pixy] All initial checks past!

[pixy] Preparing for calculation of summary statistics: pi, fst, dxy
[pixy] Data set contains 3 population(s), 1 chromosome(s), and 90 sample(s)
[pixy] Window size: 10000 bp

[pixy] Started calculations at 18:10:55 on 2021-05-07
[pixy] Using 1 out of 8 available CPU cores

[pixy] Processing chromosome/contig PvP01_01_v1...
[pixy] Calculating statistics for region PvP01_01_v1:1-156579...
KeyError: nan

**Comment by ksamuk** [comment]
Hi there! It is not immediately clear what caused that error. Would it be possible to send me a subset (~10000 lines) of your VCF, and I'll see if I can diagnose the issue on my end?

**Comment by djeffares** [comment]
Hi Kieran

Thanks so much for getting back to me. I tried with some vcfs made using bcftools this time as described in the docs:

bcftools mpileup -f hg38_pvivP01.fa -b bamlist --regions PvP01_01_v1:10000-20000 | \
bcftools call -m -Oz -f GQ -o PvP01_01_v1.10000-20000.bcftools.vcf.gz --output-type z  &

And another with ploidy 1 (as my species is haploid). vcfs attached.

Here are the files. This time I get a more informative error:

[pixy] pixy 1.0.4.beta1
[pixy] See documentation at https://pixy.readthedocs.io/en/latest/
/Users/ucbtdje/opt/anaconda3/lib/python3.8/site-packages/allel/io/vcf_read.py:1732: UserWarning: invalid INFO header: '##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">\n'
  warnings.warn('invalid INFO header: %r' % header)

[pixy] Validating VCF and input parameters...
[pixy] Checking write access...OK
[pixy] Checking CPU configuration...OK
[pixy] Checking for invariant sites...OK
[pixy] Checking chromosome data...OK
[pixy] Checking intervals/sites...OK
[pixy] Checking sample data...OK
[pixy] All initial checks past!

[pixy] Preparing for calculation of summary statistics: pi, fst, dxy
[pixy] Data set contains 3 population(s), 1 chromosome(s), and 90 sample(s)
[pixy] Window size: 1000 bp

[pixy] Started calculations at 11:44:51 on 2021-05-08
[pixy] Using 1 out of 8 available CPU cores

[pixy] Processing chromosome/contig PvP01_01_v1...
[pixy] Calculating statistics for region PvP01_01_v1:1-20000...
/Users/ucbtdje/opt/anaconda3/lib/python3.8/site-packages/allel/io/vcf_read.py:1732: UserWarning: invalid INFO header: '##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">\n'
  warnings.warn('invalid INFO header: %r' % header)
KeyError: nan



best wishes
/Dan





On 7 May 2021, at 23:51, Kieran Samuk ***@***.***> wrote:


Hi there! It is not immediately clear what caused that error. Would it be possible to send me a subset (~10000 lines) of your VCF, and I'll see if I can diagnose the issue on my end?

**Comment by ksamuk** [comment]
Hi Dan, I am not seeing your attachments, can you provide a dropbox/drive link or email them to me at ksamuk@gmail.com? I am guessing the problem has something to do with how haploid genotypes are represented.

**Comment by djeffares** [comment]
Thanks - I shared the vcfs and indexes.

best wishes
/Dan




On 8 May 2021, at 15:39, Kieran Samuk ***@***.***> wrote:


Hi Dan, I am not seeing your attachments, can you provide a dropbox/drive link or email them to me at ***@***.*** ***@***.***>? I am guessing the problem has something to do with how haploid genotypes are represented.

**Comment by ksamuk** [comment]
Hi Dan, 

Just ran the sample data you sent me, and I haven't been able to reproduce the error. Can you confirm that you get the error with the sample data? If not, can you send me some data that does produce the error?

**Comment by ksamuk** [comment]
Hi Dan, 

Very mysterious! I will see if I can get the error on my Mac today. Can you possibly share your populations file?
