### ISSUE TITLE
chromosome and zarr_path

### ISSUE THREAD

**Issue by 15787833237** [ksamuk/pixy#33]
**Describe the bug**
I don't know the chromosome and zarr_path how to write ,I guess my transcriptome data which don't include chromosome but only contig 'ID'

**The pixy command and error message**
Please copy and paste the following: 
pixy --stats pi fst dxy --vcf /home/2020222040149/Vcf/snp.hardfiltered.dpth5.missing80.vcf.gz --populations /home/2020222040149/fst/pop.txt --window_size 500000 --chromosome '<ID' --zarr_path /home/2020222040149/Pixy  --variant_filter_expression DP>=10,GQ>=20 --invariant_filter_expression DP>=10,RGQ>=20 --interval_start 15000 --interval_end 400000

**OS information**
Linux

**Sample files**
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele not already represented at this location by REF and ALT">
##FILTER=<ID=FS,Description="FS > 30.0">
##FILTER=<ID=LowQual,Description="Low quality">
##FILTER=<ID=QD,Description="QD < 2.0">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block">
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another; w
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phasing set (typically the position of the first variant in the set)">
##FORMAT=<ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias.">
##GATKCommandLine=<ID=CombineGVCFs,CommandLine="CombineGVCFs --output 04-1-5.g.vcf.gz --variant L20-04-1.g.vcf.gz --variant L20-04-2.g.vcf.gz --variant L20-04-3.g.vcf.g
##GATKCommandLine=<ID=SelectVariants,CommandLine="SelectVariants --output snp.hardfiltered.vcf.gz --exclude-filtered true --restrict-alleles-to BIALLELIC --variant snp.
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=BaseQRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref base qualities">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##INFO=<ID=END,Number=1,Type=Integer,Description="Stop position of the interval">
##INFO=<ID=ExcessHet,Number=1,Type=Float,Description="Phred-scaled p-value for exact test of excess heterozygosity">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=InbreedingCoeff,Number=1,Type=Float,Description="Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared against the Hardy
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allel
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality">
##INFO=<ID=MQRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities">
##INFO=<ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth">
##INFO=<ID=RAW_MQandDP,Number=2,Type=Integer,Description="Raw data (sum of squared MQ and total depth) for improved RMS Mapping Quality calculation. Incompatible with d
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
##INFO=<ID=SOR,Number=1,Type=Float,Description="Symmetric Odds Ratio of 2x2 contingency table to detect strand bias">
##contig=<ID=L20_01_2_TRINITY_DN145008_c0_g1,length=327,assembly=reference.fasta>

**Comment by ksamuk** [comment]
Hi there, sorry you're having this problem. Before we start, can you update to the latest version of pixy? It is probably easiest to do a fresh install by removing your old pixy environment and creating a new one.

**Comment by 15787833237** [comment]
> Hi there, sorry you're having this problem. Before we start, can you update to the latest version of pixy? It is probably easiest to do a fresh install by removing your old pixy environment and creating a new one.

Dear Professor, I use the command line :conda install --yes -c conda-forge pixy ,and then it comes out :[pixy] ERROR: The vcf is not indexed with tabix. To fix this, run "tabix [filename].vcf.gz" first

**Comment by 15787833237** [comment]
I use the command line 
:pixy --stats pi fst dxy --vcf /home/2020222040149/Vcf/snp.hardfiltered.dpth5.missing80.vcf.gz --populations /home/2020222040149/fst/pop.txt --window_size 500000 --chromosome 'contig=<ID=' --interval_start 15000 --interval_end 400000 --bypass_invariant_check 'yes', 3

however it occurs :Checking chromosome data...Exception: ('[pixy] ERROR: the following chromosomes were specified but not occur in the VCF: ', ['contig=<ID=']), how I comlete the chromosome option ?

**Comment by ksamuk** [comment]
Hi there,

The --chromosome flag is used to limit pixy's calculations to specific chromosomes or contigs. When using it, you just need to specify the chromosome/contig names you want as listed in the "CHROM" column of the VCF. 

If you *do not* want calculations for specific chromosome/contigs (i.e. you want estimates for all your chromosome/contigs), you should not include this option (or the --interval_start or --interval_end options).

Also, just a note, in the vast majority of cases, `--bypass_invariant_check 'yes'` will result in incorrect estimates. You should probably not be using this if your data comes from sequenced individuals.

Hope that helps!

**Comment by ksamuk** [comment]
Closing this for now, let me know if you run into any other issues.
