### ISSUE TITLE
Haploid VCF

### ISSUE THREAD

**Issue by Jolvii85** [ksamuk/pixy#47]
Hi there,

Does pixy also work on the haploid VCF files? Do I need to convert the VCF or manipulate the output to get the correct results?

Best regards,

Wei

**Comment by ksamuk** [comment]
Hi Wei,

pixy currently only works with diploid data, apologies! Support for different ploidies is on the list of future improvements. 

Cheers,

Kieran

**Comment by AndreaGuarracino** [comment]
Hi @ksamuk,

any chance of getting feedback from you on how to "hack" Pixy to work on haploid VCF files?

I'm really enjoying your tool, but I need to figure out if it's good enough to use it in its current state on haploid VCF files. I would prefer to properly support haploid samples.
