### ISSUE TITLE
Hard or soft filtering input VCF?

### ISSUE THREAD

**Issue by mwersebe** [ksamuk/pixy#58]
Hi! 
I am trying to figure out if sites that do not pass quality filtering (e.g., for depth QUAL, etc.) should be hard or soft filtered from the input VCF file. For example in `bcftools filter`, if you supply the `-s` flag it will annotate the filter column of the VCF with what ever string you provide. Does pixy ignore sites not having PASS in this column or count them as missing data?  

Many thanks!

**Comment by ksamuk** [comment]
Hi there! Pixy expects hard filtered VCFs, and doesn't use the filter column at all. Just be careful o make sure you preserve both variant and invariant sites when filtering (see the manual for more info on how to do this).
