### ISSUE TITLE
heterozygous sites increase nucleotide diversity?

### ISSUE THREAD

**Issue by caixu0518** [ksamuk/pixy#61]
Hi Kieran,

I wonder if pixy will consider heterozygous sites when calculating π value? I found there is a high level of nucleotide diversity in the regions with higher heterozygoousity?

Best,
Xu

**Comment by ksamuk** [comment]
Hi Xu!

Good observation. Pixy definitely considers heterozygous sites in its calculations. It is also generally expected that regions with high heterozygosity will also have high nucleotide diversity. 

Hope that helps and all the best,

Kieran
