### ISSUE TITLE
can pixy be used in haploid species

### ISSUE THREAD

**Issue by wushyer** [ksamuk/pixy#65]
Hi could I ask if pixy can be used in the haploid species? Thanks
Best
Shuangyang

**Comment by ksamuk** [comment]
Not currently, but this is a planned feature!

**Comment by ksamuk** [comment]
That's good to hear, but in order for this to be fully supported, we will need to carefully validate the computed values via simulations etc., in the same way we did for diploid data.  I'd avoid using it for haploid species for now, personally!
