### ISSUE TITLE
Problem running pi on pixy

### ISSUE THREAD

**Issue by bvaditi** [ksamuk/pixy#74]
I have created a vcf file with invariant site using bcftools and pixy installation seems to be fine. Yet on running the following code

 pixy --stats pi --vcf filename.vcf.gz --populations Pops.txt --window_size 1 --output_folder Data/ --output_prefix pixytrial

Gives the error:

/home/uramakri/bvaditi/.conda/envs/pixy/lib/python3.8/site-packages/allel/io/vcf_read.py:1732: UserWarning: invalid INFO header: '##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">\n'
  warnings.warn('invalid INFO header: %r' % header)

[pixy] Validating VCF and input parameters...
[pixy] Checking write access...OK
[pixy] Checking CPU configuration...OK
[pixy] Checking for invariant sites...OK
tabix: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[pixy] Checking chromosome data...subprocess.CalledProcessError: Command 'tabix -l /home/uramakri/bvaditi/filename.vcf.gz' returned non-zero exit status 127.

I am not able to figure what is causing the error. Could you please let me know?

**Comment by ksamuk** [comment]
Hi there! This looks to me like tabix may be installed incorrectly, or is conflicting with another piece of software in your environment (samtools often is the cause with libcrypto.so.1.0.0). What I'd try is to make a new conda environment for just pixy and tabix, and try running it again.

**Comment by bvaditi** [comment]
Dear Keiran,
Thanks for your response. I am able to run now but there is still the warning for vcf header. The output file has a lot of NAs. I am attaching it here. Will it be possible to check whether it is ok? Thanks and advance.
[pixytrial_pi.txt](https://github.com/ksamuk/pixy/files/11099624/pixytrial_pi.txt)

**Comment by ksamuk** [comment]
Hi there, pixy will output NAs if there is no data (variant or invariant) in the targeted window. The way to confirm that is correct is to look at your VCF and see if there are indeed no sites with non-missing genotypes in the windows with all NAs.

**Comment by kanikaghildiyal** [comment]
Hello,
While running the pixy software after converting  vcf file with invariant sites using bcftools, I am getting the following error:
UnicodeDecodeError:'utf-8' codec cant decode byte0x8b in position 1:invalid start byte

**Comment by kanikaghildiyal** [comment]
Could you please help me on this issue?
