### ISSUE TITLE
Hello, While running the pixy software after converting vcf file with invariant sites using bcftools, I am getting the following error:UnicodeDecodeError: 'utf-8' codec cant decode byte 0x8b in position 1: invalid start byte; Could you please help me to resolve this error? 

### ISSUE THREAD

**Issue by kanikaghildiyal** [ksamuk/pixy#76]

**Comment by ksamuk** [comment]
Hi there, pixy currently doesn't support sample or chromosome/contig names with special characters, particularly semi-colons, commas, or letters with accent characters etc. We are hoping to resolve this in a future release. In the meantime, the solution is to simplify your sample or chromosome/contig names before running pixy.

**Comment by kanikaghildiyal** [comment]
Hi,

Thank you for the suggestion!
I tried to make changes in the vcf file and it looks like this now:

[image: image.png]
However, I am still getting the same error: unicode decode error: 'utf-8'
codec cant decode byte 0x8b in position 1: invalide start byte

Could you please help me with this?

Thanks and regards,
Kanika

**Comment by ksamuk** [comment]
Hi, unfortunately, pixy doesn't have support for this type of dataset at the moment, so you'll have to wait until we fully address this issue in a later release.

**Comment by amanda128891** [comment]
Hi there, 

I know you closed this issue but I just ran into the same problem. I'm going to try to rework the sample names in my VCF but if this issue could be addressed that would make things a lot easier!

Thanks, 
-Amanda
