### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by glaudelrio** [ksamuk/pixy#77]
Hi! I am having trouble running pixy... I had worked with it before, and this is the first time this error message is produced...

pixy --stats pi fst dxy --vcf vcf_filtered_075.vcf.gz --populations populations.txt --window_size 50000 --n_cores 8

[pixy] pixy 1.2.4.beta1
[pixy] See documentation at https://pixy.readthedocs.io/en/latest/
AttributeError: module 'allel' has no attribute 'read_vcf_headers'

any idea, on what the issue is? 
thank you for any help you can provide.

**Comment by ksamuk** [comment]
I don't think so, at present, but I haven't had time to do extensive testing. We're working on a new major version of pixy, and we'll likely ensure full 3.9 compatibility for that release.

**Comment by glaudelrio** [comment]
No problem, I got it running on python 3.8.
I guess you can close the issue!
Thank you for your help.
cheers
