### ISSUE TITLE
Support for New Missing Data Formatting from GATK

### ISSUE THREAD

**Issue by ksamuk** [ksamuk/pixy#78]
GATK has implemented a (quite radical) new way of encoding missing data, that we will need to support going forward:
https://gatk.broadinstitute.org/hc/en-us/articles/6012243429531

**Comment by ChenJuiYANG** [comment]
Hi Kieran, 

I wonder what the result would be for the current version with the new GATK-generated vcf file as input. Does the results reliable?
Any suggestion if the new GATK-generated vcf file is not applicable? 

Cheers, 
Chen-Jui

**Comment by ksamuk** [comment]
Hi Chen-Jui,

I'm not quite sure at the moment, that is going to be a complex fix to implement. In the meantime, a quick fix might be to preprocess your data using bcftools to set genotypes with DP < 1 to "." as below:

bcftools +setGT your.vcf.gz -- -t q -n . -e 'FMT/DP>=1'

Cheers,

Kieran

**Comment by ksamuk** [comment]
This is now addressed in the latest version of pixy.

**Comment by ChenJuiYANG** [comment]
Just noticed that this issue only present in GATK versions 4.2.3.0 through 4.5.0.0. As the website noted: 

> ⚠️ NOTE ⚠️ This article describes behavior present in GATK versions 4.2.3.0 through 4.5.0.0, and is obsolete as of [GATK 4.6.0.0](https://github.com/broadinstitute/gatk/releases/tag/4.6.0.0), which (by overwhelming popular demand!) reverted back to the standard ./. representation in our joint genotyping tools and GenomicsDB.

Not sure how this affects pixy. Hope it has no impact.
