### ISSUE TITLE
Version of numpy and htslib doesn't work

### ISSUE THREAD

**Issue by conJUSTover** [ksamuk/pixy#82]
Thanks for developing pixy! I am currently trying to install it via conda, but I'm coming across a version issue where the newest numpy and htslib libraries are not supported by pixy. Could you please update the README with the versions of these libraries that you initially used to install this correctly? Thanks!

**Comment by conJUSTover** [comment]
I found the correct versions and pixy is now working for me. Here are the steps I used for install in case others have similar issues: 

```
conda install -c bioconda htslib openssl=1.0
conda install -c conda-forge pixy numpy=1.23.4
```

**Comment by ksamuk** [comment]
Thanks, Justin! I am planning on a major update this summer, so this might get resolved as a part of that. Good to have the fix on file for others though, much appreciated.
