### ISSUE TITLE
Overestimation of  number differences?

### ISSUE THREAD

**Issue by lisagrigoreva** [ksamuk/pixy#88]
Hi, 
I was trying to play with files and reproduce the logic from the paper.
I calculated Pi for a 10pb window per site
I have 3 individuals 
0/0
0/0
1/1
The total number of differences is 8 and the number of comparisons is 15 (6 to 2 combinations).
The only way that you can get 8 is (2 differences * 2 alleles) + (2 differences * 2 alleles)=8
However, in the VCF file the number of alleles is already taken into account.
Could you please clarify, why Pixy calculates 8, not 4?

Thank you!

**Comment by ksamuk** [comment]
Hi There,

In order to look into this, I will need a reproducible example (VCF + pixy command) of the bug. 

Cheers,

Kieran
