### ISSUE TITLE
"the provided VCF appears to contain no invariant sites"

### ISSUE THREAD

**Issue by MafaldaSFerreira** [ksamuk/pixy#89]
I am running pixy with per chromosome vcf files containing variant and invariant sites. However, for some of the files, pixy reports that there are no invariant sites and fails with the following error:

`Checking for invariant sites...Exception: [pixy] ERROR: the provided VCF appears to contain no invariant sites (ALT = "."). This check can be bypassed via --bypass_invariant_check 'yes'.`

I am running pixy with the following command (this is an example for chromosome 10):

`pixy --stats pi fst dxy --populations population_files/clusters_v01.txt --vcf chromosomes_maf0.01/herring_sentieon_125ind_230722_filter_setGT_miss0.2.vcf.minDP4.0maxDP3.0avg_miss0.2.maf0.01.ALLSites.chr10.vcf.gz --window_size 20000 --n_cores 2 --output_folder results/clusters_v01_maf0.01_20231011 --output_prefix clusters_v01.chr10.maf0.01.20kb.popgenpixy.out`

I do have invariant sites in the vcf files. Here is a small subset of such sites for chromosome 10:

`bcftools view --max-ac 2:nref herring_sentieon_125ind_230722_filter_setGT_miss0.2.vcf.minDP4.0maxDP3.0avg_miss0.2.maf0.01.ALLSites.chr10.vcf.gz | bcftools query -f '%CHROM\t%REF\t%ALT\t[%GT\t ]\n' | head -n1000 > chr10.maf0.01.1000.invariant.txt`

And if I run bcftools stats on the vcf of chromosome 10, it says the total number of no-Alts is 17184629, whereas the number of SNPs is 492509 (also attaching the output of bcftools stats).

The only thing I could think of is that in this particular vcf the variant sites start before the invariant sites... Would that trigger the warning?

[chr10.maf0.01.1000.invariant.txt](https://github.com/ksamuk/pixy/files/12866559/chr10.maf0.01.1000.invariant.txt)
[herring_sentieon_125ind_230722_filter_setGT_miss0.2.vcf.minDP4.0maxDP3.0avg_miss0.2.maf0.01.ALLSites.chr10.stats.txt](https://github.com/ksamuk/pixy/files/12866567/herring_sentieon_125ind_230722_filter_setGT_miss0.2.vcf.minDP4.0maxDP3.0avg_miss0.2.maf0.01.ALLSites.chr10.stats.txt)

**Comment by ksamuk** [comment]
Hi There!

The check for invariant sites is fairly conservative, so if you are 100% sure that you have invariant sites correctly represented in your vcf, you can bypass the check by including `--bypass_invariant_check 'yes'`.

**Comment by MafaldaSFerreira** [comment]
I did run with —bypass_invariant_check “yes” but the results I got for the dxy scan were quite strange. Blocks of very high dxy interspersed with blocks of dxy 0 across a chromosome… Which don’t look like anything I have seen before for other datasets I have worked with in the species. Maybe there is something funky in our filtering this time, and I will double check that first and come back if I have further questions.

Thanks,
Mafalda

**Comment by AliBasuony2022** [comment]
Hi Mafalda,

I hope you are doing well and happy new year.
We have met on 2021 in the ASM meeting in Tuscan, Arizona. I'm Ali from Egypt who was delivered a talk about foxes. I hope you still remember that.

I'm just wondering how did you filtered invariants? I split the all sites vcf to variant and invariants, and then filtered each one separately followed by concatenate in one vcf file? Filtering of variants (SNPs) seems straightforward, but I'm just confused how to filter invariants. I think, we shouldn't filter invariants!!! I have an invariants file with many missing data and when filtered (using relatively a similar parameters as for SNPs), it dropped more than 99% of the data ( from 116,000,000 to 1,000,000 lines). The pixy worked very well till the end and produced the plots, but I'm not sure if this is correct or there is something to do with invariants.

Any help will be appreciable.
Thanks
Ali
