### ISSUE TITLE
tabix: error while loading shared libraries: libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by lounaDeO** [ksamuk/pixy#93]
Hi!

I install pixy using following conda install commands:
`conda create --name pixy`
`conda activate pixy`
`conda install --yes -c conda-forge pixy`
`conda install --yes -c bioconda htslib`

But when I want to use pixy with this command:
`pixy --stats pi --vcf allPOP.combineGVCF.filter.4fold.10%NA.PASS.vcf.gz --populations pop.txt --window_size 10000 --n_cores 4`

I have the following error:

[pixy] pixy 1.2.7.beta1
[pixy] See documentation at https://pixy.readthedocs.io/en/latest/

[pixy] Validating VCF and input parameters...
[pixy] Checking write access...OK
[pixy] Checking CPU configuration...OK
[pixy] Checking for invariant sites...OK
tabix: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[pixy] Checking chromosome data...subprocess.CalledProcessError: Command 'tabix -l allPOP.combineGVCF.filter.4fold.10%NA.PASS.vcf.gz' returned non-zero exit status 127.

It seems I have an issue with the tabix command but I don't know how to fix it.
Any help would be really appreciated.

Thanks in advance!
Louna

**Comment by lounaDeO** [comment]
Yes, it seems to be installed:
`which tabix`
/kingdoms/tools/anaconda3/envs/pixy/bin/tabix

**Comment by lounaDeO** [comment]
Oh yes it works! thank you very much for your help!

**Comment by ksamuk** [comment]
Excellent, glad to hear it!
