### ISSUE TITLE
conda install issues with numpy and samtools

### ISSUE THREAD

**Issue by seanharrington256** [ksamuk/pixy#94]
I installed pixy via conda on a Linux cluster using: 

```
conda create -n pixy -y
conda activate pixy
conda install --yes -c conda-forge pixy python=3.8
conda install --yes -c bioconda htslib
```

Attempting to run `pixy --version` caused an error: AttributeError: module 'numpy' has no attribute 'typeDict'

I fixed this by downgrading numpy:
`conda install numpy=1.21`

When trying to actually run pixy, I then ran into an issue with tabix: 

tabix: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

I managed to fix this by installing samtools 1.9: 

`conda install -c bioconda samtools=1.9 --force-reinstall -y`

It now seems to be running well and is able to generate output.

**Comment by ksamuk** [comment]
Thanks Sean, I am going to update the installation procedure to make sure these issues no longer arise.
