### ISSUE TITLE
How to generate a allsite vcf file based on the vcf file from 1000 Genomes Project

### ISSUE THREAD

**Issue by JianhuaWang95** [ksamuk/pixy#96]
Hi Kieran,

I want to use pixy to calculate the pi values for some genes using the vcf file downloaded from 1000 Genomes Project. I do not have the bam file, is there any other way that I can use to generate a vcf file with both invariant and variant sites?

Thanks,
Jianhua

**Comment by ksamuk** [comment]
Hi Jianhua,

As far as a I know, it is not possible generate an allsites file without access to BAMs or gvcfs, apologies!

Kieran

**Comment by JianhuaWang95** [comment]
Got it, thanks for the info!

Best,
Jianhua
________________________________
From: Kieran Samuk ***@***.***>
Sent: Saturday, February 3, 2024 17:41
To: ksamuk/pixy ***@***.***>
Cc: Wang, Jianhua ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ksamuk/pixy] How to generate a allsite vcf file based on the vcf file from 1000 Genomes Project (Issue #96)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Jianhua,

As far as a I know, it is not possible generate an allsites file without access to BAMs or gvcfs, apologies!

Kieran
